class Error(Exception):
    pass

class miError(Error):
    pass
